export const GET_INGREDIENT_DETAILS: 'GET_INGREDIENT_DETAILS' = 'GET_INGREDIENT_DETAILS';
export const DELETE_INGREDIENT_DETAILS: 'DELETE_INGREDIENT_DETAILS' = 'DELETE_INGREDIENT_DETAILS';

export const GET_INDGREDIETNS_REQUEST:'GET_INDGREDIETNS_REQUEST' = 'GET_INDGREDIETNS_REQUEST';
export const GET_INDGREDIETNS_REQUEST_SUCCESS:'GET_INDGREDIETNS_REQUEST_SUCCESS' = 'GET_INDGREDIETNS_REQUEST_SUCCESS';
export const GET_INDGREDIETNS_REQUEST_FAILED:'GET_INDGREDIETNS_REQUEST_FAILED' = 'GET_INDGREDIETNS_REQUEST_FAILED';

export const CREATE_ORDER_REQUEST:'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const ORDER_REQUEST_FAILED:'ORDER_REQUEST_FAILED' = 'ORDER_REQUEST_FAILED';
export const ORDER_REQUEST_SUCCESS:'ORDER_REQUEST_SUCCESS' = 'ORDER_REQUEST_SUCCESS';

export const ADD_INGREDIENT:'ADD_INGREDIENT' = "ADD_INGREDIENT";
export const SET_BUN:'SET_BUN' = "SET_BUN";
export const DELETE_INGREDIENT:'DELETE_INGREDIENT' = "DELETE_INGREDIENT";
export const MOVE_INGREDIENT:'MOVE_INGREDIENT' = "MOVE_INGREDIENT";
export const RESET_BURGER:'RESET_BURGER' = "RESET_BURGER";

export const SET_INGREDIENTS:'SET_INGREDIENTS' = "SET_INGREDIENTS";

export const SET_SELECTED_INGREDIENT:'SET_SELECTED_INGREDIENT' = 'SET_SELECTED_INGREDIENT';
export const CLEAR_SELECTED_INGREDIENT:'CLEAR_SELECTED_INGREDIENT' = 'CLEAR_SELECTED_INGREDIENT';

export const SET_ACCEPTED_ORDER:'SET_ACCEPTED_ORDER' = 'SET_ACCEPTED_ORDER';
export const CLEAR_ACCEPTED_ORDER:'CLEAR_ACCEPTED_ORDER' = 'CLEAR_ACCEPTED_ORDER';

export const LOGIN_REQUEST:'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS:'LOGIN_REQUEST_SUCCESS' = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED:'LOGIN_REQUEST_FAILED' = 'LOGIN_REQUEST_FAILED';

export const LOGOUT_REQUEST:'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS:'LOGOUT_REQUEST_SUCCESS' = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILED:'LOGOUT_REQUEST_FAILED' = 'LOGOUT_REQUEST_FAILED';

export const REGISTER_REQUEST:'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESS:'REGISTER_REQUEST_SUCCESS' = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILED:'REGISTER_REQUEST_FAILED' = 'REGISTER_REQUEST_FAILED';

export const FORGOT_PASSWORD_REQUEST:'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_REQUEST_SUCCESS:'FORGOT_PASSWORD_REQUEST_SUCCESS' = 'FORGOT_PASSWORD_REQUEST_SUCCESS';
export const FORGOT_PASSWORD_REQUEST_FAILED:'FORGOT_PASSWORD_REQUEST_FAILED' = 'FORGOT_PASSWORD_REQUEST_FAILED';

export const RESET_PASSWORD_REQUEST:'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST_SUCCESS:'RESET_PASSWORD_REQUEST_SUCCESS' = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAILED:'RESET_PASSWORD_REQUEST_FAILED' = 'RESET_PASSWORD_REQUEST_FAILED';

export const REFRESH_TOKEN_REQUEST:'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_REQUEST_SUCCESS:'REFRESH_TOKEN_REQUEST_SUCCESS' = 'REFRESH_TOKEN_REQUEST_SUCCESS';
export const REFRESH_TOKEN_REQUEST_FAILED:'REFRESH_TOKEN_REQUEST_FAILED' = 'REFRESH_TOKEN_REQUEST_FAILED';

export const GET_USER_DATA_REQUEST:'GET_USER_DATA_REQUEST' = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_REQUEST_SUCCESS:'GET_USER_DATA_REQUEST_SUCCESS' = 'GET_USER_DATA_REQUEST_SUCCESS';
export const GET_USER_DATA_REQUEST_FAILED:'GET_USER_DATA_REQUEST_FAILED' = 'GET_USER_DATA_REQUEST_FAILED';

export const UPDATE_USER_DATA_REQUEST:'UPDATE_USER_DATA_REQUEST' = 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_REQUEST_SUCCESS:'UPDATE_USER_DATA_REQUEST_SUCCESS' = 'UPDATE_USER_DATA_REQUEST_SUCCESS';
export const UPDATE_USER_DATA_REQUEST_FAILED:'UPDATE_USER_DATA_REQUEST_FAILED' = 'UPDATE_USER_DATA_REQUEST_FAILED';

export const AUTHORIZATION_STATE:'AUTHORIZATION_STATE' = 'AUTHORIZATION_STATE';

export const SET_USER_DATA:'SET_USER_DATA' = 'SET_USER_DATA';

export const SET_FORGOTTEN_PASSWORD:'SET_FORGOTTEN_PASSWORD' = 'SET_FORGOTTEN_PASSWORD';











