export const GET_INGREDIENT_DETAILS = 'GET_INGREDIENT_DETAILS';
export const DELETE_INGREDIENT_DETAILS = 'DELETE_INGREDIENT_DETAILS';

export const GET_INDGREDIETNS_REQUEST = 'GET_INDGREDIETNS_REQUEST';
export const GET_INDGREDIETNS_REQUEST_SUCCESS = 'GET_INDGREDIETNS_REQUEST_SUCCESS';
export const GET_INDGREDIETNS_REQUEST_FAILED = 'GET_INDGREDIETNS_REQUEST_FAILED';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const ORDER_REQUEST_FAILED = 'ORDER_REQUEST_FAILED';
export const ORDER_REQUEST_SUCCESS = 'ORDER_REQUEST_SUCCESS';

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const SET_BUN = "SET_BUN";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const MOVE_INGREDIENT = "MOVE_INGREDIENT";

export const SET_INGREDIENTS = "SET_INGREDIENTS";

export const SET_SELECTED_INGREDIENT = 'SET_SELECTED_INGREDIENT';
export const CLEAR_SELECTED_INGREDIENT = 'CLEAR_SELECTED_INGREDIENT';
export const SET_ACCEPTED_ORDER = 'SET_ACCEPTED_ORDER';
export const CLEAR_ACCEPTED_ORDER = 'CLEAR_ACCEPTED_ORDER';



